### ISSUE TITLE
steps beyond `npm i && npm start`?

### ISSUE THREAD

**Issue by jdalton** [openfin/node-integration-example#3]
Hi!

When I run the example app with `npm start` I'm getting:

<img src="https://user-images.githubusercontent.com/4303/31845705-a004e67c-b5b8-11e7-8c05-b86c8da139db.png" width="75%">

with no errors or anything logged to the page or dev console.

I'm using using node v8.7.0 (npm v5.5.1) though I tried node v6.10.3 with no luck either.
Any pointers?

**Comment by nkolba** [comment]
If you tried running this example previously, you may have an old version of the node asset cached.  In \AppData\Local\OpenFin\apps there will be a directory for the app with an 'assets\node-service' directory.  Deleting the node-service and then re-running should clear up the problem.

**Comment by jdalton** [comment]
Is there an OS X equiv path?

**Comment by jdalton** [comment]
I don't think I've run this previously. First time cloning the repo.

**Comment by nkolba** [comment]
@jdalton There's going to be some things in this example that are windows specific (not all features are cross-platform today).  Can you try on Windows?

**Comment by jdalton** [comment]
Ah yep, it works on Windows. Are there plans to add an OS X example?
